// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wikipage.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Wiki struct {
	Pages                []*Page  `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wiki) Reset()         { *m = Wiki{} }
func (m *Wiki) String() string { return proto.CompactTextString(m) }
func (*Wiki) ProtoMessage()    {}
func (*Wiki) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dc00b1f7631e10d, []int{0}
}

func (m *Wiki) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wiki.Unmarshal(m, b)
}
func (m *Wiki) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wiki.Marshal(b, m, deterministic)
}
func (m *Wiki) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wiki.Merge(m, src)
}
func (m *Wiki) XXX_Size() int {
	return xxx_messageInfo_Wiki.Size(m)
}
func (m *Wiki) XXX_DiscardUnknown() {
	xxx_messageInfo_Wiki.DiscardUnknown(m)
}

var xxx_messageInfo_Wiki proto.InternalMessageInfo

func (m *Wiki) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

type Page struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Links                []string `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Categories           []string `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Templates            []string `protobuf:"bytes,5,rep,name=templates,proto3" json:"templates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dc00b1f7631e10d, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Page) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Page) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Page) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Page) GetTemplates() []string {
	if m != nil {
		return m.Templates
	}
	return nil
}

func init() {
	proto.RegisterType((*Wiki)(nil), "protobuf.Wiki")
	proto.RegisterType((*Page)(nil), "protobuf.Page")
}

func init() { proto.RegisterFile("wikipage.proto", fileDescriptor_6dc00b1f7631e10d) }

var fileDescriptor_6dc00b1f7631e10d = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0xeb, 0xc2, 0x30,
	0x10, 0x47, 0x49, 0x9b, 0xfe, 0xf9, 0xf7, 0x84, 0x0e, 0xc1, 0x21, 0x83, 0x48, 0x28, 0x0e, 0x1d,
	0xa4, 0x83, 0x7e, 0x11, 0xe9, 0xe2, 0x9c, 0xda, 0xb3, 0x1c, 0xad, 0x36, 0x34, 0x27, 0xae, 0x7e,
	0x74, 0x49, 0x8a, 0xe8, 0x74, 0xbc, 0xf7, 0x6e, 0xf8, 0x41, 0xf1, 0xa4, 0x81, 0x9c, 0xed, 0xb1,
	0x76, 0xf3, 0xc4, 0x93, 0xfa, 0x8f, 0xa7, 0x7d, 0x5c, 0xcb, 0x3d, 0xc8, 0x33, 0x0d, 0xa4, 0x76,
	0x90, 0x85, 0xee, 0xb5, 0x30, 0x69, 0xb5, 0x3a, 0x14, 0xf5, 0xe7, 0xa3, 0x3e, 0xd9, 0x1e, 0x9b,
	0x25, 0x96, 0x2f, 0x01, 0x32, 0xb0, 0x2a, 0x20, 0xa1, 0x4e, 0x0b, 0x23, 0x2a, 0xd9, 0x24, 0xd4,
	0xa9, 0x35, 0x64, 0x4c, 0x3c, 0xa2, 0x4e, 0x8c, 0xa8, 0xf2, 0x66, 0x81, 0x60, 0x47, 0xba, 0x0f,
	0x5e, 0xa7, 0x26, 0x0d, 0x36, 0x82, 0xda, 0x02, 0x5c, 0x2c, 0x63, 0x3f, 0xcd, 0x84, 0x5e, 0xcb,
	0x98, 0x7e, 0x8c, 0xda, 0x40, 0xce, 0x78, 0x73, 0xa3, 0x65, 0xf4, 0x3a, 0x8b, 0xf9, 0x2b, 0xda,
	0xbf, 0x38, 0xec, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xc2, 0x68, 0xf7, 0xd3, 0x00, 0x00,
	0x00,
}
