// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wikipage.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Wiki struct {
	Pages                []*Page  `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wiki) Reset()         { *m = Wiki{} }
func (m *Wiki) String() string { return proto.CompactTextString(m) }
func (*Wiki) ProtoMessage()    {}
func (*Wiki) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dc00b1f7631e10d, []int{0}
}

func (m *Wiki) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wiki.Unmarshal(m, b)
}
func (m *Wiki) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wiki.Marshal(b, m, deterministic)
}
func (m *Wiki) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wiki.Merge(m, src)
}
func (m *Wiki) XXX_Size() int {
	return xxx_messageInfo_Wiki.Size(m)
}
func (m *Wiki) XXX_DiscardUnknown() {
	xxx_messageInfo_Wiki.DiscardUnknown(m)
}

var xxx_messageInfo_Wiki proto.InternalMessageInfo

func (m *Wiki) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

type Page struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Links                []string `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Categories           []string `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Templates            []string `protobuf:"bytes,5,rep,name=templates,proto3" json:"templates,omitempty"`
	NamedEntityIDs       []uint32 `protobuf:"varint,6,rep,packed,name=namedEntityIDs,proto3" json:"namedEntityIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dc00b1f7631e10d, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Page) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Page) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Page) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Page) GetTemplates() []string {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *Page) GetNamedEntityIDs() []uint32 {
	if m != nil {
		return m.NamedEntityIDs
	}
	return nil
}

type Data struct {
	NamedEntities        []*NamedEntity `protobuf:"bytes,1,rep,name=namedEntities,proto3" json:"namedEntities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dc00b1f7631e10d, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetNamedEntities() []*NamedEntity {
	if m != nil {
		return m.NamedEntities
	}
	return nil
}

type NamedEntity struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JpName               string   `protobuf:"bytes,2,opt,name=jpName,proto3" json:"jpName,omitempty"`
	EnName               string   `protobuf:"bytes,3,opt,name=enName,proto3" json:"enName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedEntity) Reset()         { *m = NamedEntity{} }
func (m *NamedEntity) String() string { return proto.CompactTextString(m) }
func (*NamedEntity) ProtoMessage()    {}
func (*NamedEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dc00b1f7631e10d, []int{3}
}

func (m *NamedEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedEntity.Unmarshal(m, b)
}
func (m *NamedEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedEntity.Marshal(b, m, deterministic)
}
func (m *NamedEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedEntity.Merge(m, src)
}
func (m *NamedEntity) XXX_Size() int {
	return xxx_messageInfo_NamedEntity.Size(m)
}
func (m *NamedEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedEntity.DiscardUnknown(m)
}

var xxx_messageInfo_NamedEntity proto.InternalMessageInfo

func (m *NamedEntity) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NamedEntity) GetJpName() string {
	if m != nil {
		return m.JpName
	}
	return ""
}

func (m *NamedEntity) GetEnName() string {
	if m != nil {
		return m.EnName
	}
	return ""
}

func init() {
	proto.RegisterType((*Wiki)(nil), "protobuf.Wiki")
	proto.RegisterType((*Page)(nil), "protobuf.Page")
	proto.RegisterType((*Data)(nil), "protobuf.Data")
	proto.RegisterType((*NamedEntity)(nil), "protobuf.NamedEntity")
}

func init() { proto.RegisterFile("wikipage.proto", fileDescriptor_6dc00b1f7631e10d) }

var fileDescriptor_6dc00b1f7631e10d = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x49, 0x93, 0x16, 0xef, 0x3b, 0xda, 0x21, 0xa8, 0x64, 0x10, 0x09, 0x45, 0xa4, 0x83,
	0x74, 0xd0, 0xd1, 0xd1, 0x73, 0x70, 0x50, 0x24, 0x8b, 0x73, 0xce, 0xc6, 0xf2, 0xd9, 0x5e, 0x5b,
	0x2e, 0x11, 0xf1, 0x1f, 0xf9, 0x33, 0x25, 0x69, 0xb5, 0xf5, 0xa6, 0xf0, 0x3e, 0xcf, 0x1b, 0x3e,
	0x5e, 0xc8, 0x3e, 0xb1, 0xc1, 0x41, 0xd7, 0xa6, 0x1c, 0xf6, 0xbd, 0xeb, 0xf9, 0x51, 0x78, 0xb6,
	0x1f, 0x6f, 0xf9, 0x15, 0xb0, 0x17, 0x6c, 0x90, 0x5f, 0x40, 0xec, 0xbd, 0x15, 0x44, 0xd2, 0x62,
	0x7d, 0x9d, 0x95, 0xbf, 0x8d, 0xf2, 0x59, 0xd7, 0x46, 0x8d, 0x32, 0xff, 0x26, 0xc0, 0x7c, 0xe6,
	0x19, 0x44, 0x58, 0x09, 0x22, 0x49, 0xc1, 0x54, 0x84, 0x15, 0x3f, 0x86, 0xd8, 0xa1, 0x6b, 0x8d,
	0x88, 0x24, 0x29, 0x56, 0x6a, 0x0c, 0x9e, 0xb6, 0xd8, 0x35, 0x56, 0x50, 0x49, 0x3d, 0x0d, 0x81,
	0x9f, 0x03, 0xbc, 0x6a, 0x67, 0xea, 0x7e, 0x8f, 0xc6, 0x0a, 0x16, 0xd4, 0x82, 0xf0, 0x33, 0x58,
	0x39, 0xb3, 0x1b, 0x5a, 0xed, 0x8c, 0x15, 0x71, 0xd0, 0x33, 0xe0, 0x97, 0x90, 0x75, 0x7a, 0x67,
	0xaa, 0xfb, 0xce, 0xa1, 0xfb, 0x7a, 0xd8, 0x58, 0x91, 0x48, 0x5a, 0xa4, 0xea, 0x80, 0xe6, 0x77,
	0xc0, 0x36, 0xda, 0x69, 0x7e, 0x0b, 0xe9, 0x6c, 0xf0, 0x6f, 0xe0, 0xc9, 0x3c, 0xf0, 0x69, 0xfe,
	0xa8, 0xfe, 0x77, 0xf3, 0x47, 0x58, 0x2f, 0xec, 0x62, 0x75, 0x1a, 0x56, 0x9f, 0x42, 0xf2, 0x3e,
	0xf8, 0xc2, 0x34, 0x7b, 0x4a, 0x9e, 0x9b, 0x2e, 0x70, 0x3a, 0xf2, 0x31, 0x6d, 0x93, 0x70, 0xf3,
	0xe6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x09, 0xe6, 0xab, 0xbe, 0x8f, 0x01, 0x00, 0x00,
}
